### PR TITLE
Task/eslint format part 2

### PR DESCRIPTION
**Pull request by B0ER**
## Description
Resolved eslint problems.
- ~~deleted some unused components~~
- deleted unused variables
- deleted unused imports
- added prop-validation into components
- added sonarjs rules
- added eslint tool to pre-commit hook (code will be checked on rules before committing)

### CODE REVIEW

**Comment by B0ER** [comment]
Will open the PR after the app testing

**Comment by B0ER** [comment]
@MenlyCSE, after PR is checked, please merge it as 'Squash and merge'
It's needed to have clear story of commits in git history for main branch.

the function creates one commit for this PR and merging.

**Review by MenlyCSE — APPROVED** [review]
Job well done! I'll test for IOS and Android

**Comment by MenlyCSE** [comment]
Whoops! I realized that I forgot to squash and merge. Sorry about this. 
I'll avoid reverting so it doesn't add additional commits to the history

**Comment by B0ER** [comment]
I tested it on android before put it to ready for PR

**Pull request merged**
